version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: taskhub
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=taskhub
      - DATABASE_USER=taskuser
      - DATABASE_PASSWORD=taskpass
      - DATABASE_HOST=db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

volumes:
  postgres_data:
